name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Sync
        run: uv sync
      - name: Type Check
        run: uv run ty check custom_components
      - name: Lint
        run: uv run ruff check .
      - name: Format Check
        run: uv run ruff format --check custom_components
