name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Sync
        run: task setup
      - name: Check
        run: task check
